### ISSUE TITLE
Might not be as HA as we think

### ISSUE THREAD

**Issue by krancour** [deis/etcd#1]
The RC doesn't do anything to ensure the peers are scheduled to different k8s nodes.  I'm not sure k8s even _has_ semantics that permit that.  This could be a _big _ problem because if a majority of the etcd pods get assigned to a single k8s node and that node dies (or even just becomes unreachable due to network issues) then quorum is lost.  This scenario is not only possible, but it's also not at all unlikely.

**Comment by bacongobbler** [comment]
we can modify the scheduling policy to our needs. If HA is what we need, then we can allocate a higher weight for that :)

Our scheduling policy is at https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L273-L280

**Comment by rimusz** [comment]
I did talk with Butcher of enforcing etcd pods on to different nodes too :) otherwise there is no HA for etcd at all.

**Comment by bacongobbler** [comment]
closing as out of scope for etcd. This is better done by tuning the scheduler kubernetes to deploy pods in a highly available manner. This sort of behaviour is not available at the manifest level.

**Comment by krancour** [comment]
fwiw, @kmala was telling me that the scheduler already makes a best effort to distribute replicas across hosts.  In general, he said that if you have n hosts and m replicas, with n > m, then no one host should get more than one replica.  I can't find where in the k8s documentation this is states, but truthfully, I haven't gone looking for it yet.  If this is _not_ the case, then I would agree that upstream scheduler improvements are required to address this.

@technosophos has also explained the strategy of new etcd pods checking with the k8s API to find out how many replicas are _actually_ running and then self-promoting from a proxy to peer if needed.  (I wish we could do that in 1.x, actually, but without the second source of truth that is the API, we can't.)  That is a cool feature.  And if an etcd cluster is ever lost in its entirety, it seems his intent is to make it auto-restore from a TBD backup mechanism.

Taking all of this into consideration, my initial worry that deis/etcd isn't sufficiently HA might have been unfounded.

**Comment by bacongobbler** [comment]
All great considerations though, @krancour :) I'm happy to see that you've looked into this, as getting an HA story for kubernetes is definitely important.

**Comment by kmala** [comment]
@krancour In the https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/devel/scheduler.md ,it is mentioned "it tries to spread Pods across nodes while at the same time favoring the least-loaded nodes" which means there might be a scenario where multiple pods can be scheduled on the same Node if the other Nodes are heavily loaded but the https://github.com/kubernetes/kubernetes/blob/bdac198130df43db14ded2762395871539dcfca3/plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go#L98-L111 code will make sure that if there are any less loaded nodes which doesn't have this type of Pods they will get the highest priority and pods gets scheduled on them.We can also add a predicate in the scheduler policy and restrict multiple pods of  same type landing on the same Node.This type of predicate is not present currently but can be added very easily.
