### ISSUE TITLE
Should etcd be required for Deis Workflow

### ISSUE THREAD

**Issue by krancour** [deis/etcd#10]
As we all well know from v1.x, etcd is a pain point.  This is a somewhat radical idea, but do we really _need_ it in v2?

Yes... of course we need the etcd that's _under_ k8s, but my question pertains pretty specifically to this deis/etcd that we intend to run _within_ k8s as a foundational component of v2.

Fundamentally, we use etcd for two things in v1.x-- service discovery and configuration.  If k8s has service discovery licked (especially with the dns add-on in play) and Deis already has a database where we could store more platform configuration (than we do today) _and_ already has an API which can be extended to handle those things (and can scale!) then maybe we don't need etcd after all...

Obviously, I haven't thought through every implication of this idea yet, but I think it may not me _entirely_ crazy to entertain.

Hypothetically, it could work something like this:
1. Create secret for db password in k8s namespace "deis"
2. Create rc for HA deis database (postgres); will use secret above
3. Create a service for the database
4. Create a secret for Deis API token
5. Create rc for deis API; can discover database via DNS; can mount and use secrets containing db credentials and API token
6. Create a service for the API
7. Bring up any/all other Deis components; can discover the API via DNS; can mount and use secret containing API token
8. Bonus: Would be awesome to create go bindings for the Deis API that can be reused by all the other Deis components

The biggest problem I can anticipate is that I _think_ (but I'm not positive) that deis/postgresql needs etcd to facilitate leader election and failover.  Could there be another way to accomplish that?  Or alternatively, maybe we could use etcd for that purpose and _only_ that-- just to get the DB going and then let the DB and API take it from there?

It's late, so excuse me if any of this is totally nuts... it stems pretty directly from how much more I enjoy interacting with k8s API than I do futzing with etcd-- and that's left me wishing our API and DB would handle more of the burden of maintaining and storing platform state... and it could mean one less point of failure and one less thing to have to back up.

**Comment by bacongobbler** [comment]
We don't need it for service discovery, but things like LDAP authentication and configuring the registry backend is still an unsolved problem without relying on our old config backend, etcd. I mean we could make it a requirement to tell users that they need to fork the controller, but then we'd be killing off core features.

**Comment by bacongobbler** [comment]
To be clear I don't like etcd either but I think we'd need to come up with an alternative solution to replace etcd (something kubernetes specific would be awesome) so we can retain these features.

**Comment by rimusz** [comment]
I spoke about moving away from etcd to k8s based solution with Jason and Gabe last week in San Francisco, for now the plan is to get v2 out with less effort of implementing big changes. When we have v2 for sure we need to come up with k8s specific solution.

**Comment by technosophos** [comment]
The longterm plan is that we will reduce our dependency on etcd. But there are some places where we have a strong need for a read-write k/v store. One of those is the logic that keeps Postgres HA running.

I have been looking into some of the deeper features of PG, and there are some really cool things in there -- like the ability to do a watch on a table. I think we should investigate these fully. It might actually be the case that a PG DB could solve a lot of problems in a reasonable (and truly battle-tested) way. Is that something you'd like to look into @krancour?

**Comment by krancour** [comment]
It's more than I'm prepared to take on at the moment.  I think I've got a lot to solve for on the routing/ingress front.  That being said, that road might quickly lead me to a place where I'd prefer to be dealing with an API backed by PG instead of etcd.  So maybe in the post-alpha timeframe my work will lead me here.

**Comment by slack** [comment]
Since we are well on the way to ripping out etcd, do we want to close this one?

Refs deis/workflow#96

**Comment by slack** [comment]
Closing, etcd out for Deis v2.
