### ISSUE TITLE
make kube-rc should use sed instead of perl

### ISSUE THREAD

**Issue by jchauncey** [deis/etcd#24]
We should change this so it works like the other make files. Instead of using perl to replace the image in the original file we should make tmp files and use those to create the rcs.

**Comment by bacongobbler** [comment]
for reference, we still need to make this change upstream too at deis/prototype-repo. Helm became the de-facto way to install these components so we've been sticking to that for now, but yeah we should revisit this.

**Comment by arschles** [comment]
+1. applies to many of our other repositories as well. cc/ @sgoings, as I think his [makeup](https://github.com/sgoings/makeup) and related projects could cover such functionality

**Comment by jchauncey** [comment]
ive got this ready ill submit a PR shortly

**Comment by technosophos** [comment]
You guys collectively undermined my beautiful perl.
