### ISSUE TITLE
etcd fails to contact API server on certain clusters.

### ISSUE THREAD

**Issue by technosophos** [deis/etcd#29]
@rimusz and @jchauncey have both seen errors like this:

```
$ kubectl --namespace=deis logs deis-etcd-1-i3ywx
[error] 2015/12/18 20:44:34 Failed aboutme.FromEnv: Get https://10.100.0.1:443/api/v1/namespaces/deis/pods/deis-etcd-1-i3ywx: EOF
[warning] 2015/12/18 20:44:34 Attempting to recover.
[warning] 2015/12/18 20:44:34 No IP found by API query.
```

What is happening here is that the pod is contacting the Kube API server to get information about itself. The server _appears_ to be returning an empty response. That surprises me, though a failed SSL negotiation would not have.

Really, what we need to do is get into that pod and fire off a request to API to find out what is going on.

**Comment by jchauncey** [comment]
I think I am seeing a very similar issue with deis/router

**Comment by rimusz** [comment]
the problem is caused by enabling 'runtime_config=extensions/v1beta1=true,extensions/v1beta1/daemonsets=true`
