### ISSUE TITLE
Single node etcd cluster possible?

### ISSUE THREAD

**Issue by krancour** [deis/etcd#35]
Should it be possible to run one?  I tried editing the deis/deis-dev chart to use just one replica and a cluster size of 1, but anything that depended on etcd still went into a CrashLoopBackOff waiting for the etcd cluster to come up.

**Comment by ghost** [comment]
@krancour I bootstrap Deis-LIte with etcd cluster size 1, it works just fine.
You have to edit two manifest files deis-etcd-discovery-rc.yaml and deis-etcd-rc.yaml and change
`DEIS_ETCD_CLUSTER_SIZE` to 1

**Comment by krancour** [comment]
I had overlooked the fact that cluster size had to be set in the disco rc as well.  Trying this before I close.

**Comment by Instaresearch** [comment]
Thanks @instaresearch for mentioning `Deis-LIte` .
@krancour I did the same mistake at first too when I was making Deis-Lite charts:)

**Comment by krancour** [comment]
I confirmed this is all set if I remember to edit the disco rc as well.

**Comment by bacongobbler** [comment]
> disco rc

:dancer:
