### ISSUE TITLE
etcd Alpha Requirements

### ISSUE THREAD

**Issue by slack** [deis/etcd#7]
To prove out the deis v2 integration we need to cut a release of deis/etcd that:
- [x] Deployable to K8S: Service def, RC def, repository follows [standard Deis pattern](https://github.com/technosophos/prototype-repo)
- [ ] Installable by Helm (opt)
- [x] Is useable by deis/workflow components
- [x] Installation instructions documented in README
- [x] Installation linked to alpha setup in deis/workflow

The implementation for alpha does not need:
- HA
- Backups
- Recovery

**Comment by rimusz** [comment]
:+1:

**Comment by technosophos** [comment]
We appear to have hit all of the requirements. The helm installation "optional requirement" will be satisfied externally in the `deis/charts` repo.
